# Shell variables
# Generated by 'wal'
wallpaper='/home/ag/.config/wall.png'

# Special
background='#060911'
foreground='#c4cddb'
cursor='#c4cddb'

# Colors
color0='#060911'
color1='#A17460'
color2='#345588'
color3='#61708B'
color4='#7888A1'
color5='#7C98C2'
color6='#8C99AE'
color7='#c4cddb'
color8='#898f99'
color9='#A17460'
color10='#345588'
color11='#61708B'
color12='#7888A1'
color13='#7C98C2'
color14='#8C99AE'
color15='#c4cddb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
